Repository cds-snc/digital-canada-ca, pull requests merged in 2019-09, with the labels that each got.

#1038 Enable sitemap generation
  config/_default/config.yaml
  layouts/_default/baseof.html
Labels: enhancement

#1031 Update GOC header/footer.
  assets/sass/cds/_base.scss
  assets/sass/cds/_layout.scss
  assets/sass/cds/_nav.scss
  i18n/en.yaml
  i18n/fr.yaml
  layouts/index.html
  layouts/partials/footer-links.html
  layouts/partials/footer.html
  layouts/partials/menu.html
  static/img/cds/goc--footer-logo.svg
Labels: enhancement

#1032 Update contact us styles.
  assets/sass/cds/_components.scss
  assets/sass/cds/_layout.scss
  i18n/en.yaml
  i18n/fr.yaml
  layouts/partials/contact-info.html
  layouts/partials/social-links.html
Labels: enhancement

#1034 Update blog section of homepage.
  assets/sass/cds/_base.scss
  assets/sass/cds/_sections.scss
  assets/sass/cds/_social-font.scss
  i18n/en.yaml
  i18n/fr.yaml
  layouts/index.html
Labels: enhancement

#1033 Update newsletter subscription section.
  assets/sass/cds/_base.scss
  assets/sass/cds/_sections.scss
  i18n/en.yaml
  i18n/fr.yaml
  layouts/index.html
  layouts/partials/mailing-list.en.html
  layouts/partials/mailing-list.fr.html
  layouts/partials/mailing-list.html
Labels: enhancement

#1037 Update main homepage content.
  assets/sass/cds/_sections.scss
  content/en/_index.html
  content/fr/_index.html
  i18n/en.yaml
  i18n/fr.yaml
  layouts/index.html
Labels: enhancement

#1046 Update products shown on homepage
  content/en/products/products/help-canadians-access-the-cpp-disability-benefit.md
  content/en/products/products/help-canadians-with-low-income-file-taxes.md
  content/en/products/products/make-it-easier-to-identify-tender-opportunities.md
  content/en/products/products/notify.md
  content/fr/products/products/aider-les-canadiennes-et-les-canadiens-à-recevoir-des-prestations-d’invalidité-du-rpc.md
  content/fr/products/products/aider-les-canadiens-à-faible-revenu-à-produire-leur-déclaration-fiscale.md
  content/fr/products/products/faciliter-le-repérage-d’appels-d’offres.md
  content/fr/products/products/notify.md
  layouts/index.html
Labels: enhancement

#1035 Update styles of our team section.
  assets/sass/cds/_layout.scss
  assets/sass/cds/_sections.scss
  content/en/_index.html
  content/fr/_index.html
  layouts/index.html
  static/img/cds/team-photo.jpg
Labels: enhancement

#1047 Fixup Read The Blog on French site
  content/fr/blog/_index.md
  i18n/fr.yaml
Labels: bug

#1048 Update French translation of "Past Products"
  i18n/fr.yaml
Labels: bug

#1072 Contrast fixes for Keith
  assets/sass/cds/_base.scss
  assets/sass/cds/_variables.scss
  i18n/en.yaml
  i18n/fr.yaml
  layouts/section/partnerships.html
Labels: accessibility, bug
